package com.atguigu.springboot01.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class InterfaceLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.LOG_ID
     *
     * @mbg.generated
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.SRC_SYS
     *
     * @mbg.generated
     */
    private String srcSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.TGT_SYS
     *
     * @mbg.generated
     */
    private String tgtSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.INTERFACE_NAME
     *
     * @mbg.generated
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.REQ_CONTENT
     *
     * @mbg.generated
     */
    private String reqContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.REQ_TIME
     *
     * @mbg.generated
     */
    private Date reqTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.RSP_CONTENT
     *
     * @mbg.generated
     */
    private String rspContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.RES_CODE
     *
     * @mbg.generated
     */
    private String resCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.RES_DESC
     *
     * @mbg.generated
     */
    private String resDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.RSP_TIME
     *
     * @mbg.generated
     */
    private Date rspTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.IS_AUTO
     *
     * @mbg.generated
     */
    private Short isAuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.ERR_INFO
     *
     * @mbg.generated
     */
    private String errInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_INTERFACE_LOG.REC_TIME
     *
     * @mbg.generated
     */
    private Date recTime;



	private String srcSysName;


	private String tgtSysName;

	private String isAutoName;
}
